name: Build Image

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'
  push:

env:
  IMAGE_NAME: dpvduncan/bazarr:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: all

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Install jq
      uses: dcarbone/install-jq-action@v2

    - name: Prepare variables
      run: |
        BAZARR_RELEASE=$(curl -s https://api.github.com/repos/morpheus65535/bazarr/releases/latest | jq -r '.tag_name')
        bazarr_url=$(curl -k -s https://api.github.com/repos/morpheus65535/bazarr/releases/tags/${BAZARR_RELEASE} | jq -r '.assets[].browser_download_url')
        curl -o bazarr.zip -L "${bazarr_url}"
        echo "BAZARR_RELEASE=${SONARR_RELEASE}" >> ${GITHUB_ENV}

    - name: Build
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: |
          linux/amd64
        push: true
        tags: ${{ env.IMAGE_NAME }}
        build-args: |
          BAZARR_RELEASE=${{ env.BAZARR_RELEASE }}
